In [3]:
import numpy as np

In [13]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [14]:
a[0]

1

In [15]:
a[1]

2

In [16]:
import time
import sys

In [19]:
b=range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [24]:
c = np.arange(1000)
print(c.size*c.itemsize)

4000


In [26]:
size=1000000

In [27]:
L1=range(size)
L2=range(size)
A1=np.arange(size)
A2=np.arange(size)

In [35]:
start=time.time()
result=[(x+y) for x,y in zip(L1,L2)]
result=[(x+y) for x,y in zip(L1,L2)]
print("Python list took:",(time.time()-start)*1000)


Python list took: 258.52513313293457


In [36]:
start=time.time()
result=A1+A2
print("numpy array took:",(time.time()-start)*1000)


numpy array took: 17.537832260131836


In [40]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a.ndim

2

In [42]:
a.itemsize

4

In [43]:
a.shape

(3, 2)

In [45]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [46]:
a.itemsize

8

In [47]:
a.shape

(3, 2)

In [50]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.complex128)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
l=range(5)
l

range(0, 5)

In [55]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
print("concat example:")
print(np.char.add(['hello','hi'],['abc','def']))

concat example:
['helloabc' 'hidef']


In [5]:
print(np.char.center('hello',20,fillchar= '-' ))

-------hello--------


In [6]:
print(np.char.capitalize('hello world'))

Hello world


In [7]:
print(np.char.title('how are you doing?'))

How Are You Doing?


In [10]:
print(np.char.lower(["HELLO","WORLD"]))
print(np.char.lower('HELLO'))

['hello' 'world']
hello


In [15]:
print(np.char.upper('python is easy'))

PYTHON IS EASY


In [16]:
print(np.char.upper(['python','data']))

['PYTHON' 'DATA']


In [17]:
print(np.char.split('are you coming to the party?'))

['are', 'you', 'coming', 'to', 'the', 'party?']


In [18]:
print(np.char.splitlines("Hello\nhow are you?"))

['Hello', 'how are you?']


In [21]:
print(np.char.strip(['nina','admin','anaitha'],'a'))

['nin' 'dmin' 'naith']


In [23]:
print(np.char.join([':','-'],['dmy','ymd']))

['d:m:y' 'y-m-d']


In [24]:
print(np.char.replace('He is a good dancer','is','was'))

He was a good dancer
